[package]
name = "no_math"
version = "0.1.0"
authors = ["Miloš Spasojević <milos.s.pfc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
