[package]
name = "stocking_stuffer"
version = "0.1.0"
authors = ["irreal <milos.spasojevic.tms@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
